name: CI

on:
  pull_request:
  push:
    branches: [main, dev]
    paths-ignore: [.gitignore, LICENSE, README.md]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ join(matrix.*, ', ') }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:
          - { plat: android, os: ubuntu-latest, arch: armeabi-v7a, toolchain: ndk, mode: debug, args: --setup_toolchains="ndk 28.0" }
          - { plat: android, os: ubuntu-latest, arch: armeabi-v7a, toolchain: ndk, mode: releasedbg, args: --setup_toolchains="ndk 28.0" }
          - { plat: android, os: ubuntu-latest, arch: arm64-v8a, toolchain: ndk, mode: debug, args: --setup_toolchains="ndk 28.0" }
          - { plat: android, os: ubuntu-latest, arch: arm64-v8a, toolchain: ndk, mode: releasedbg, args: --setup_toolchains="ndk 28.0" }

          - { plat: iphoneos, os: macos-latest, arch: arm64, toolchain: xcode, mode: debug }
          - { plat: iphoneos, os: macos-latest, arch: arm64, toolchain: xcode, mode: releasedbg }
          - { plat: macosx, os: macos-latest, arch: arm64, toolchain: xcode, mode: debug }
          - { plat: macosx, os: macos-latest, arch: arm64, toolchain: xcode, mode: releasedbg }

          - { plat: linux, os: ubuntu-latest, arch: x86_64, toolchain: clang, mode: debug, compiler: llvm-19 }
          - { plat: linux, os: ubuntu-latest, arch: x86_64, toolchain: clang, mode: releasedbg, compiler: llvm-19 }
          - { plat: linux, os: ubuntu-latest, arch: x86_64, toolchain: gcc, mode: debug }
          - { plat: linux, os: ubuntu-latest, arch: x86_64, toolchain: gcc, mode: releasedbg }

          - { plat: wasm, os: ubuntu-latest, arch: wasm32, toolchain: emcc, mode: debug, args: --setup_toolchains=y }
          - { plat: wasm, os: ubuntu-latest, arch: wasm32, toolchain: emcc, mode: releasedbg, args: --setup_toolchains=y }
          - { plat: wasm, os: ubuntu-latest, arch: wasm64, toolchain: emcc, mode: debug, args: --setup_toolchains=y }
          - { plat: wasm, os: ubuntu-latest, arch: wasm64, toolchain: emcc, mode: releasedbg, args: --setup_toolchains=y }

          - { plat: windows, os: windows-latest, arch: x64, toolchain: clang-cl, mode: debug, args: --dev=n }
          - { plat: windows, os: windows-latest, arch: x64, toolchain: clang-cl, mode: releasedbg, args: --dev=n }
          - { plat: windows, os: windows-latest, arch: x86, toolchain: msvc, mode: debug, args: --dev=n }
          - { plat: windows, os: windows-latest, arch: x86, toolchain: msvc, mode: releasedbg, args: --dev=n }
          - { plat: windows, os: windows-latest, arch: x64, toolchain: msvc, mode: debug, args: --dev=n }
          - { plat: windows, os: windows-latest, arch: x64, toolchain: msvc, mode: releasedbg, args: --dev=n }

          - { plat: macosx, os: macos-latest, arch: arm64, toolchain: xcode, mode: release, compiler: apple-clang-16.0.0, args: --dev=n }
          - { plat: linux, os: ubuntu-latest, arch: x86_64, toolchain: clang-19, mode: release, compiler: llvm-19.0.0, args: --dev=n }
          - { plat: linux, os: ubuntu-latest, arch: x86_64, toolchain: gcc-12, mode: release, compiler: gcc-12, args: --dev=n }

          - { plat: linux, os: ubuntu-latest, arch: x86_64, toolchain: gcc, mode: releasedbg, args: --cxx_version=c++23 }

          - { plat: linux, os: ubuntu-latest, arch: x86_64, toolchain: clang, mode: releasedbg, compiler: llvm-21, args: --use_modules=y --dev=n }
#          - { plat: linux, os: ubuntu-latest, arch: x86_64, toolchain: clang, mode: releasedbg, compiler: llvm-21, args: --use_modules=y  --use_std_module=y }

          - { plat: linux, os: ubuntu-latest, arch: x86_64, toolchain: clang, mode: debug, compiler: llvm-19, san: asan, args: --asan=y --lsan=y --ubsan=y }
          - { plat: linux, os: ubuntu-latest, arch: x86_64, toolchain: clang, mode: debug, compiler: llvm-19, san: tsan, args: --tsan=y }

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@3a1a5dddfc7fa625d9a698738334bf55655a861a # v1.2.5
        with:
          xmake-version: 3.0.7
          actions-cache-folder: .xmake-cache
          package-cache: true
          package-cache-key: ${{ matrix.plat }}_${{ matrix.arch }}_${{ matrix.toolchain }}_${{ matrix.mode }}_${{ matrix.san }}
          build-cache: true
          build-cache-key: ${{ matrix.plat }}_${{ matrix.arch }}_${{ matrix.toolchain }}_${{ matrix.mode }}_${{ matrix.san }}

      - name: Setup Cpp
        if: matrix.compiler
        uses: aminya/setup-cpp@1f17f92d6a52bfcb1a25348e2c526c2e5cbb1134 # v1.8.0
        with:
          compiler: ${{ matrix.compiler }}

      - name: Config and dependencies
        run: | # zizmor: ignore[template-injection] Matrix is static.
          xmake f -vy -p ${{ matrix.plat }} -a ${{ matrix.arch }} --toolchain=${{ matrix.toolchain }} -m ${{ matrix.mode }} ${{ matrix.args }}

      - name: Build and run tests
        run: xmake test -v
