name: Mutation Testing

on:
  pull_request:
  push:
    branches: [main, dev]
    paths-ignore: [.gitignore, LICENSE, README.md]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ join(matrix.*, ', ') }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    permissions:
      contents: read # Only needed for private repos.
    strategy:
      fail-fast: false
      matrix:
        include:
          - { plat: linux, os: ubuntu-latest, arch: x86_64, toolchain: clang, mode: releasedbg, version: 19 }

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@3a1a5dddfc7fa625d9a698738334bf55655a861a # v1.2.5
        with:
          xmake-version: 3.0.7
          actions-cache-folder: .xmake-cache
          package-cache: true
          package-cache-key: ${{ matrix.plat }}_${{ matrix.arch }}_${{ matrix.toolchain }}_${{ matrix.mode }}
          build-cache: true
          build-cache-key: ${{ matrix.plat }}_${{ matrix.arch }}_${{ matrix.toolchain }}_${{ matrix.mode }}

      - name: Setup Cpp
        uses: aminya/setup-cpp@1f17f92d6a52bfcb1a25348e2c526c2e5cbb1134 # v1.8.0
        with:
          compiler: llvm-${{ matrix.version }}

      - name: Setup mull
        run: | # zizmor: ignore[template-injection] Matrix is static.
          curl -1sLf 'https://dl.cloudsmith.io/public/mull-project/mull-stable/setup.deb.sh' | sudo -E bash
          sudo apt-get install mull-${{ matrix.version }}

      - name: Config and dependencies
        run: | # zizmor: ignore[template-injection] Matrix is static.
          xmake f -vy --ccache=n -p ${{ matrix.plat }} -a ${{ matrix.arch }} --toolchain=${{ matrix.toolchain }} -m ${{ matrix.mode }} ${{ matrix.args }}

      - name: Run mull
        run: xmake mull --group="*|bench" --mutation_score_threshold=50
